<?php
    $lang['number']   = 'FACTURE N°';
    $lang['date']     = 'Date';
    $lang['time']     = 'Heure de facturation';
    $lang['due']      = 'Echéance';
    $lang['to']       = 'Client';
    $lang['from']     = 'Prestataire';
    $lang['product']  = 'Produit';
    $lang['qty']      = 'Quantité';
    $lang['price']    = 'Prix unit. HT';
    $lang['discount'] = 'Réduction';
    $lang['vat']      = 'TVA';
    $lang['total']    = 'Total';
    $lang['page']     = 'Page';
    $lang['page_of']  = 'sur';
